### ISSUE TITLE
Buy Digital Ocean droplet

### ISSUE THREAD

**Issue by hynguyen2610** [mgm-interns/teamradio2-frontend#235]
Hi @dat-ng and @mgm-sfrank, as we discussed about using paid service (should not be too costly) to deploy TeamRadio, we had mention Digital Ocean Standard popular droplet. You can see it here:

https://www.digitalocean.com/pricing/

4 GB | 2 vCPUs | 80 GB | 4 TB | $20/mo $0.030/hr

As the code is growing and nearly reach the limit that free heroku can ensure the stablility (sometimes the server will die when building due to memory problem), I think there should be someone goes forward and make this task done.

As @dat-ng said, this service will have monthly billing, so I think it will be better if company buy this service and provide it for the team.

**Comment by mgm-sfrank** [comment]
This is fine for me, we can rent this service

**Comment by hynguyen2610** [comment]
We will use AWS instead
