### ISSUE TITLE
Anonymous station

### ISSUE THREAD

**Issue by hynguyen2610** [mgm-interns/teamradio2-frontend#256]
Please reference to this: https://github.com/mgm-interns/team-radio/issues/121

This is the content of that ticket:

As a new user, I want to try out team radio, so I create a station immediately (without registering as a user) - and then I can't add any songs. I feel like being tricked into signing a membership I did not want

Acceptance criteria

after creating a station as an anonymous user, I can add songs to the playlist
other anonymous users can't add songs
when I register as a user, the station is assigned to me and appears in the "my stations" list

**Comment by NguyenTatNhac** [comment]
Done in #322
