### ISSUE TITLE
Station player gets choked when there are 2 or more duplicated songs playing continuosly

### ISSUE THREAD

**Issue by pvtri96** [mgm-interns/teamradio2-frontend#259]
# Steps to reproduce:

- Join a station with login 
- Add 2 or more duplicated songs to the playlist

### Actual behavior

- After the second song start playing, the player jumps to a random seeking position

### Expected behavior

- The second song should start from the 00:00

**Comment by hynguyen2610** [comment]
It's not very important and acceptable. Let's close it now
