### ISSUE TITLE
Recent station UI in User profile has some different

### ISSUE THREAD

**Issue by hynguyen2610** [mgm-interns/teamradio2-frontend#275]
Reproduce:
Loggin and visit user profile

Old version:
![image](https://user-images.githubusercontent.com/15276320/39693940-d859e786-520f-11e8-9031-49802367c463.png)

Current version:
![image](https://user-images.githubusercontent.com/15276320/39693961-e6bf573e-520f-11e8-998f-8e7276155cb5.png)

**Comment by NguyenAnhQuoc1994** [comment]
It's done
