### ISSUE TITLE
Missing feature: One user can join only one station at a time

### ISSUE THREAD

**Issue by hynguyen2610** [mgm-interns/teamradio2-frontend#299]
Description:

User A is in station S1, with two browser B1 and B2.

If in B1, user join station S2, B2 should redirect user to station S2 as well.

If in B2, user join station S3, B1 should redirect user to station S3 as well.

In short, if a user open TeamRadio in many tabs, they can join only one station at a time.

**Comment by NguyenTatNhac** [comment]
please refer to: https://github.com/mgm-interns/team-radio/issues/89

**Comment by hynguyen2610** [comment]
At the moment, this is not a high priority task.
