### ISSUE TITLE
Online number is not change after user leave station

### ISSUE THREAD

**Issue by NguyenTatNhac** [mgm-interns/teamradio2-frontend#304]
How to re-procedure:
- Goto development site
- Login first
- Join to any station
- Switch to another

Expected:
- Number online of the previous station is reduce after switch to next staion

Actual:
- Number online of the previous station doesn't change after switch to next staion

**Comment by hynguyen2610** [comment]
@Tran-Hoang-Lam : I think you are working on it, can you assign it to you and move it to In Progress?

**Comment by hynguyen2610** [comment]
Fixed
