### ISSUE TITLE
Server stage usually has a problem

### ISSUE THREAD

**Issue by LoanPhuongHoang** [mgm-interns/teamradio2-frontend#345]
Server stage usually has a problem. Then uses could not log in or join station. It has notification that "Internal server error". To log in, users have to click log in button 2 times.
Expected: server stage should work properly and users could log in with only 1 click

**Comment by hynguyen2610** [comment]
Hi @LoanPhuongHoang , please confirm if this error is present in current version. I've done a test but I can login with 1 lick.

**Comment by LoanPhuongHoang** [comment]
Dear @hynguyen2610, this error does not happen always and the percentage of this error is 5%. That is the reason why I use the word "usually". But it mean that our server has problems and it is unstable.

**Comment by hynguyen2610** [comment]
Since we had moved to Google Cloud, and we had spent two days for testing without seeing this. I think it was fixed at the moment. Could you please have a look again?
