### ISSUE TITLE
"Invalid access token" error message should not be displayed in frontend.

### ISSUE THREAD

**Issue by hynguyen2610** [mgm-interns/teamradio2-frontend#362]
This error message should NOT be displayed in user interface.

![image](https://user-images.githubusercontent.com/15276320/40041514-70fc8190-5848-11e8-9072-203f389b8fb5.png)

**Comment by xstars1505** [comment]
Cannot re-produce for now

**Comment by NguyenTatNhac** [comment]
@xstars1505 It should be in todo if it has not been fixed!
It's not done yet

**Comment by hynguyen2610** [comment]
Now it's really done 💯
