### ISSUE TITLE
Bug: When create a station with an existed name, a no-name station page would be displayed

### ISSUE THREAD

**Issue by hynguyen2610** [mgm-interns/teamradio2-frontend#373]
![image](https://user-images.githubusercontent.com/15276320/40100950-047f70d6-5910-11e8-9942-89cf1efd4c94.png)

The backend response code is 400, with an error message "id has been existed". I think frontend can check the error code and show the correct message to user

**Comment by NguyenTatNhac** [comment]
What environment are you in?
I'm in the environment https://dev-web.teamrad.io, and when creating a station with an existing name, it appears an error message. And I was not redirected to the station page with the name empty.
I'm still in the home page.

**Comment by NguyenTatNhac** [comment]
Second, I think the error message should be edited at the server, because the user does not directly create the station id, which they create the station name. However, the frontend could do that, but it would be totally unreasonable, does not make sense.
