### ISSUE TITLE
Sort wrongly in Station List

### ISSUE THREAD

**Issue by LoanPhuongHoang** [mgm-interns/teamradio2-frontend#402]
Stations are sorted in incorrect way in station list.
When I create new station, this station is not put in the right position in station list. In fact, it comes to the end of the station list.
Expected: stations will be sort following: https://github.com/mgm-interns/team-radio/issues/101

**Comment by hynguyen2610** [comment]
Hi @LoanPhuongHoang, can you please tell us what is the difference between the current version's behaviour and the ref story?
