### ISSUE TITLE
First message in Chat box takes so long time to appear and be able for other people to read

### ISSUE THREAD

**Issue by LoanPhuongHoang** [mgm-interns/teamradio2-frontend#413]
When I create a new station and would like to chat with my friends but the first message takes so much time for my friends to be able to read. It could take even some minutes or when I type a second message, my friend could see the first message.
Expected: the message should appear immediately.

**Comment by hynguyen2610** [comment]
I think the customer requirement for this chat feature is just "some thing that user can chat", so it is not a high priority feature and we should not investigate much on it. Also, a faster and more lightweight chat solution was implemented. We can have it on stage environment today.

**Comment by LoanPhuongHoang** [comment]
It is not in high priority feature but I think it would be better if we could fix it. If you could not fix it now, you could fix it later.

**Comment by hynguyen2610** [comment]
@LoanPhuongHoang  The dev team've just tested it again but we can't found your problem. Could you please give us the reproduce steps?
